### DISCUSSION TITLE
processVanillaFile compiler result question

### DISCUSSION THREAD

**Discussion by m7yue** [vanilla-extract-css/vanilla-extract#1127] [Q&A]
### Describe the bug

here two `.css.ts` file
```ts
// share.css.ts
import { style } from '@vanilla-extract/css'

export const share1 = style({
  display: 'flex',
  fontSize: 88,
  background: 'red'
})

export const share2 = style({
  display: 'flex',
  fontSize: 180,
  background: 'red'
})
```
```ts
// a.css.ts
import { share1 } from './share.css'
import { style } from '@vanilla-extract/css'

export const testStyle = style({
  display: 'flex',
  fontSize: 180,
  background: 'red'
})

export {
  share1
}
```
when i use  `processVanillaFile`, `compile` api to compile `a.css.ts`, i find the result contain the whole style of `share.css.ts`, but i just want  `share1` result !
```css
.share__djlmpd0 {
  display: flex;
  font-size: 88px;
  background: red;
}
.share__djlmpd1 {
  display: flex;
  font-size: 180px;
  background: red;
}
.a__n4rpv30 {
  display: flex;
  font-size: 180px;
  background: red;
}
```

### Reproduction

unneed

### System Info

```shell
System:
    OS: macOS 11.5.1
    CPU: (8) x64 Apple M1
    Memory: 21.36 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 14.1.2
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
