### DISCUSSION TITLE
Responsive variant recipes

### DISCUSSION THREAD

**Discussion by timkinsman** [vanilla-extract-css/vanilla-extract#1586] [Show and tell]
Howdy! 🤠 

I've created a package which is an extension of `@vanilla-extract/recipes` that adds responsive variants. Tailwind variants is the inspiration behind the `responsiveVariants` functionality (before it was [discontinued](https://www.tailwind-variants.org/docs/tailwind-v4#breaking-changes))

### Setup

`createHomemadeRecipe` accepts key/value pairs where the keys become your responsive modifiers, and the values are the min-width where that breakpoint should start.

```ts
// homemade-recipe.css.ts
import { createHomemadeRecipe } from "homemade-recipes";

export const homemadeRecipe = createHomemadeRecipe({
  /** Phones (landscape) */
  xs: "520px",
  /** Tablets (portrait) */
  sm: "768px",
  /** Tablets (landscape) */
  md: "1024px",
  /** Laptops */
  lg: "1280px",
  /** Desktops */
  xl: "1640px",
});
```

`homemadeRecipe` extends [recipe](https://vanilla-extract.style/documentation/packages/recipes/#recipe) that accepts an optional `responsiveVariants`.

```ts
// button-recipe.css.ts
import { HomemadeRecipeVariants } from "homemade-recipes";
import { homemadeRecipe } from "./homemade-recipe.css";

export const buttonRecipe = homemadeRecipe({
  base: {
    borderRadius: 6,
  },

  variants: {
    fullWidth: {
      true: {
        width: "100%",
      },
      false: {
        width: "unset",
      },
    },
    variant: {
      bright: "bright",
    },
  },

  responsiveVariants: ["sm"],
});

export type ButtonVariants = NonNullable<
  HomemadeRecipeVariants<typeof buttonRecipe>
>;
```

> `responsiveVariants: ["sm"]` will generate an additional set of classes at build time.

```css
.button-recipe__4lwr860 {
  border-radius: 6px;
}
.button-recipe_fullWidth_true__4lwr861 {
  width: 100%;
}
.button-recipe_fullWidth_false__4lwr862 {
  width: unset;
}
+ @media screen and (min-width: 768px) {
+   .button-recipe_fullWidth_sm_true__4lwr863 {
+     width: 100%;
+   }
+   .button-recipe_fullWidth_sm_false__4lwr864 {
+     width: unset;
+   }
+ }
```

[appendCss](https://github.com/timkinsman/homemade-recipes/blob/main/packages/homemade-recipes/src/sheet.ts#L69) will generate (at runtime).

```html
<style
  data-package="homemade-recipes"
  data-identifier="homemade-recipe__1qtsqlc0"
  type="text/css"
>
  @media screen and (min-width: 768px) {
    .bright_sm {
      color: orange;
      font-family: Arial;
    }
  }
</style>
```

> By passing in an existing class to the recipe (i.e. [bright](https://github.com/timkinsman/homemade-recipes/blob/main/apps/vite/src/index.css#L45)), `bright_sm` can now be created.

With this homemade recipe, you can now use it for your button component.

```tsx
// button.tsx
import { ButtonVariants, buttonRecipe } from "./button-recipe.css";

type ButtonProps = ButtonVariants;

export const Button = ({ fullWidth, variant }: ButtonProps) => {
  return (
    <button className={buttonRecipe({ fullWidth, variant })}>
      Hello world
    </button>
  );
};
```

### Usage

```tsx
// App.tsx
import "./App.css";
import { Button } from "./button";

function App() {
  return (
    <Button
      // fullWidth?: boolean | { initial?: boolean; sm?: boolean; }
      fullWidth={{ initial: true, sm: false }}
      // variant?: "bright" | { initial?: "bright"; sm?: "bright"; }
      variant={{ sm: "bright" }}
    />
  );
}

export default App;
```

The following CSS classes will be applied to your `Button` component.

```
button-recipe__1d33wle0 button-recipe_fullWidth_true__1d33wle1 button-recipe_fullWidth_sm_false__1d33wle5 bright_sm
```

The classes

```css
.button-recipe__4lwr860 {
  border-radius: 6px;
}

.button-recipe_fullWidth_true__4lwr861 {
  width: 100%;
}

@media screen and (min-width: 768px) {
  .button-recipe_fullWidth_sm_false__4lwr864 {
    width: unset;
  }
}

@media screen and (min-width: 768px) {
  .bright_sm {
    color: orange;
    font-family: Arial;
  }
}
```

[The example.](https://github.com/timkinsman/homemade-recipes/tree/main/apps/vite)

[Full README](https://github.com/timkinsman/homemade-recipes/blob/main/packages/homemade-recipes/README.md)

---

[Source code](https://github.com/timkinsman/homemade-recipes/tree/main/packages/homemade-recipes)

More examples
- [Standalone UI package.](https://github.com/timkinsman/homemade-recipes/tree/main/packages/ui)
- [Next.js 15 (app router) consuming UI package.](https://github.com/timkinsman/homemade-recipes/tree/main/apps/next)

Feel free to fork, use, or contribute by raising discussions or issues. Since I use this package in my personal projects, I'm committed to continually improving it. 😃

## Installation

```sh
npm install homemade-recipes
```
```sh
pnpm install homemade-recipes
```
```sh
yarn add homemade-recipes
```
