### DISCUSSION TITLE
What is the equivalent of mixin?

### DISCUSSION THREAD

**Discussion by HeartSquared** [vanilla-extract-css/vanilla-extract#258] [Q&A] [answered]
@namliw and I have been experimenting and we can't seem to figure out what the equivalent of a mixin would be.

The use case we have is something like this, where we have shared styles between different selectors (`composeStyles` doesn't look suitable since they're not on the same level - not sure if it even works beyond the base either):

```ts
export const navItem = style({
  selectors: {
    '&:hover::after': {
      backgroundColor: tokens.colour.bulbasaur,
      top: '50%',
      bottom: `calc(${HIGHLIGHT_OVERFLOW} * -1)`,
    },
  },
});

export const navItemActive = style({
  '::after': {
    backgroundColor: tokens.colour.pikachu,
    top: '50%',
    bottom: `calc(${HIGHLIGHT_OVERFLOW} * -1)`,
  },
  },
});
```

How would we achieve something equivalent to this pattern?

```scss
@mixin highlight($bg-color) {
      backgroundColor: $bg-color,
      top: 50%,
      bottom: `calc(${HIGHLIGHT_OVERFLOW} * -1)`,
}

.navItem {
    &:hover::after {
      @extend highlight(tokens.colour.bulbasaur);
    }
  };

.navItemActive {
  &::after {
      @extend highlight(tokens.colour.pikachu);
  }
}
```
