### DISCUSSION TITLE
Need help in writing complex selectors.

### DISCUSSION THREAD

**Discussion by tawhidurrahman** [vanilla-extract-css/vanilla-extract#293] [Q&A]
## I need help in writing these complex selector styles. 
How should I write the below scss selector styles in vanilla-extract?

```scss
.btn {
  &.disabled,
  &:disabled,
  &[disabled],
  fieldset[disabled] & {
      &,
      &:hover,
      &:focus,
      &.focus,
      &:active,
      &.active {
          background-color: #333;
          border-color: #444;
      }
    }
}
```

or this

```scss
.btn {
  &:hover,
  &:focus,
  &:not(:disabled):not(.disabled):active,
  &:not(:disabled):not(.disabled).active,
  &:not(:disabled):not(.disabled):active:focus,
  &:not(:disabled):not(.disabled).active:focus,
  &:active:hover,
  &.active:hover,
  .visible > &.toggle,
  .visible > &.toggle:focus,
  .visible > &.toggle:hover {
      background-color: #222;
      color: #666;
      box-shadow: none;
  }
}
```
