### DISCUSSION TITLE
Nested use of variables in themes

### DISCUSSION THREAD

**Discussion by ksesong** [vanilla-extract-css/vanilla-extract#405] [Q&A] [answered]
Hi,

I am trying to port an existing stylesheet into `vanilla-extract`, which uses a previously defined variable to define itself, something like:

```css
:root {
  --rgb-white: 255, 255, 255;
  --color-background: rgb(var(--rgb-white));
}
```

How can I achieve this with `vanilla-extract`? I guess the option of `globalStyle` is still possible, but I wonder whether there is a better solution.
