### DISCUSSION TITLE
How to make sprinkles shorthands for multiple properties

### DISCUSSION THREAD

**Discussion by mattstobbs** [vanilla-extract-css/vanilla-extract#461] [Q&A] [answered]
When using sprinkles, is it possible to create shorthands to combine multiple properties? For example, tailwindcss has the class:
```css
.text-xs {
  font-size: 0.75rem;
  line-height: 1rem;
}
```
Is it possible to create a 'textXS' shorthand? Kind of like a recipe but less specific.
