### DISCUSSION TITLE
fallback for same style property

### DISCUSSION THREAD

**Discussion by juyeong1260** [vanilla-extract-css/vanilla-extract#481] [Q&A] [answered]
```scss
.body {
  padding: constant(safe-area-inset-top) 0 constant(safe-area-inset-bottom);
  padding: env(safe-area-inset-top) 0 env(safe-area-inset-bottom);
}
```

I want to give a fallback to a property like this, how can I do it in vanilla-extract?
