### DISCUSSION TITLE
sprinkles array value

### DISCUSSION THREAD

**Discussion by JiangWeixian** [vanilla-extract-css/vanilla-extract#573] [Q&A]
If I define follow sprinkles

```ts
import { defineProperties, createSprinkles } from '@vanilla-extract/sprinkles'

const unResponsiveStyles = defineProperties({
   bg: {
      fixed: {
         background-attachment: fixed;
      },
      repeat: {
         background-repeat: repeat; 
      }
   }
})

export const sprinkles = createSprinkles(responsiveStyles)
```

is able to be used it in this way

```ts
const cx = sprinkles({
   bg: ['fixed', 'repeat']
})
```

it means

```css
{
    background-attachment: fixed;
    background-repeat: repeat; 
}
```
