### DISCUSSION TITLE
fontface font-weight support

### DISCUSSION THREAD

**Discussion by y-nk** [vanilla-extract-css/vanilla-extract#596] [Q&A] [answered]
In CSS `@font-face` has the capacity to overload a font with different font file depending on the style defined in the block such as:

```css
@font-face {
  src: url(font1.ttf);
  font-weight: 400;
}

@font-face {
  src: url(font2.ttf);
  font-weight: 700;
}
```

which would naturally switch between font1 and font2 when using a `<strong>`, for example. I'm trying to achieve that, but it seems i cant - at least i'm not finding an answer yet for that (still searching). I'd like to avoid having to define a complex theme with a font { body, bold } and build a <Bold> component using this themed-based bold class ; it seems overkill just typing it.

Anybody has a clue how to achieve this? Thanks a lot all!
