### DISCUSSION TITLE
Support for manually ordering rules in the rare case it's needed

### DISCUSSION THREAD

**Discussion by DanielHeath** [vanilla-extract-css/vanilla-extract#822] [Ideas]
I have run into a slightly obscure case while overriding the rendering of an inline SVG by using `!important` to override its attribute styles.

I'm using this to change the fill color on hover.

```
  svg {
    fill: var(--svg-highlight-color) !important;
    &:hover {
      // touch browsers treat tapping on an SVG element as a hover
      // that lasts until you touch elsewhere, which breaks our
      // color toggling, so only implement hover if available.
      @media (hover)  {
        --svg-highlight-color: var(--icon-hover-state);
      }
    }
  }
  // When the button is disabled, we want no hover behavior
  // Must be last to override everything else
  [disabled] svg, [disabled] .FontAwesomeIcon_composed {
    --svg-highlight-color: var(--icon-disabled-state);
  }

```

Any idea how to adapt this to vanilla-extract? It (eg) moves media queries to the end, which breaks this pattern.

**Comment by DanielHeath** [comment]
Related: 

https://github.com/seek-oss/vanilla-extract/issues/141

https://github.com/seek-oss/vanilla-extract/discussions/734 (similar topic, but this is a specific use-case rather than "I want X")

**Comment by michaeltaranto** [comment]
Hey Daniel, it'd be great if you could share a basic example of the end result in a codepen (or similar). Demonstrating the desired static HTML and CSS you are after.

Once we have a working example, should be able to recommend the right approach using VE.

**Comment by DanielHeath** [comment]
Sure.

https://codepen.io/0xb4d1dea/pen/MWGjvMX is a basic example of how moving the media query after the `[disabled]` style causes a regression.

**Comment by DanielHeath** [comment]
Looks like I can duplicate the `[disabled]` style into the media query, which fixes it at the cost of a few wasted bytes for the duplication.

**Comment by michaeltaranto** [comment]
Ok i have a few options:
#### Option 1. Ensure the svg is not within a `disabled` container as part of the selector:
```css
svg path {
  fill: var(--icon-color, blue);
}
[disabled] {
  --icon-color: grey;
}
@media (hover) {
  div:not([disabled]) svg:hover {
    --icon-color: red;
  }
}
```
This requires consistent HTML, e.g. wrapping elements (ideally a button?) regardless of disabled state.

#### Option 2. Disable pointer events on disabled containers

```css
svg path {
  fill: var(--icon-color, blue);
}
[disabled] {
  --icon-color: grey;
  pointer-events: none;
}
@media (hover) {
  svg:hover path {
    --icon-color: red;
  }
}
```

The VE code for the latter option would look something like this:

```ts
import { createVar, fallbackVar, globalStyle } from '@vanilla-extract/css';

const iconColor = createVar();

globalStyle('svg path', {
  fill: fallbackVar(iconColor, 'blue')
});

globalStyle('[disabled]', {
  vars: {
    [iconColor]: 'grey'
  },
  pointerEvents: 'none'
});

globalStyle('svg:hover path', {
  '@media': {
    '(hover)': {
      vars: {
        [iconColor]: 'red'
      },
    }
  }
})
```

I would personally be leaning into scoped rules rather than using global selectors, but that is for you to asses based on your requirements.

Hope that helps.
