### DISCUSSION TITLE
Allow actual CSS strings?

### DISCUSSION THREAD

**Discussion by wmertens** [vanilla-extract-css/vanilla-extract#898] [Ideas]
For DX, it would be nice to be able to directly copy CSS snippets, for example from the browser devtools, so it would be nice to have a helper function that converts actual CSS to ComplexCss:

```js
style(css`
  color: red;
  background-color: white;
  &:hover {
    color: black;
  }
`)
// becomes
style({
  color: 'red',
  backgroundColor: 'white',
  '&:hover': {
    color: 'black',
  },
})
```

Is that desirable? What would the special properties like `selectors` and `vars` look like inside a template?

Looks like https://stylis.js.org could do it with a middleware

**Comment by wmertens** [comment]
extra benefit: you can transform classlists to selectors as part of the template transform instead of afterwards inside the object keys

**Comment by mattcompiles** [comment]
Personally, I'm not a fan of this being part of the core API. However I think it's nice to be able to convert from one to the other quickly. Someone has actually already built a CSS to VE converter btw: https://css-to-vanilla-extract.netlify.app/.

**Reply by astahmer** [reply]
this is great ! would it make sense to be mentioned somewhere in the docs, under an ecosystem section ?

**Comment by wmertens** [comment]
That convertor is nice but coming from styled-components it would still be nice to have the css syntax in the css.ts file.

@mattcompiles I've been playing with Stylis and I think I was able to make it. See [this StackBlitz](https://stackblitz.com/edit/qwik-starter-jzxwzm?file=src%2Froutes%2Findex.tsx,src%2Fcomponents%2Fheader%2Fve-style.ts,src%2Fcomponents%2Fheader%2Fstyled.tsx,src%2Fcomponents%2Fheader%2Fheader.tsx,src%2Fcomponents%2Fheader%2Fheader.css.ts)

I think this will work? I'm just not sure about converting classlists to selectors. When I encounter an interpolation in a selector, I check if it is a string of one or more words ending with 6 alphanumeric characters followed by digits separated by spaces. Is that always correct? I'd rather not have to dig into VE internals to grab the known identifiers.

Using my function, this css:

```scss
          // ignore me
          padding: 0.5em;
          border: thin solid var(${'--color-hint'});
          border-bottom: none;
          :focus {
            background: unsupported(123);
            background: gold;
          }
          @media screen and (min-width: 768px) {
            whatever: hello;
            :hover { color: green }
          }
          @media printer {
            // use up all the ink
            background-color: black
          }
          ${'header_header__1wihje60 oowjoq42'} + & {
            border-left: none;
          }
          @supports (display: grid) {
            display: grid;
          }
```

converts into
```json
{
  "padding": "0.5em",
  "border": "thin solid var(--color-hint)",
  "border-bottom": "none",
  "selectors": {
    ":focus": {
      "background": [
        "unsupported(123)",
        "gold"
      ]
    },
    ".header_header__1wihje60+&": {
      "border-left": "none"
    }
  },
  "@media": {
    "screen and (min-width: 768px)": {
      "whatever": "hello",
      "selectors": {
        ":hover": {
          "color": "green"
        }
      }
    },
    "printer": {
      "background-color": "black"
    }
  },
  "@supports": {
    "(display: grid)": {
      "display": "grid"
    }
  }
}
```
Is that correct?
(actually I just realized I can leave the interpolations as is, right?)
