### ISSUE TITLE
Missing style output when globalStyle and layer rules are used together

### ISSUE THREAD

**Issue by dadajam4** [vanilla-extract-css/vanilla-extract#1113]
### Describe the bug

When globalStyle and layer rules are used together in a single file, all but the last rule defined will be missing from the output.

```ts
import { globalStyle } from '@vanilla-extract/css';

export const a1 = globalStyle(':root', {
  '@layer': {
    testLayer: {
      color: 'red'
    }
  }
});

export const a2 = globalStyle(':root', {
  '@layer': {
    testLayer: {
      background: 'red'
    }
  }
});
```

## Expected Output

```css
@layer testLayer {
  :root {
    color: red;
    background: red;
  }
}
```

## Actual output

```css
@layer testLayer {
  :root {
    background: red; // color is missing.
  }
}
```

### Reproduction

https://stackblitz.com/edit/stackblitz-starters-8jxr3t?description=Starter%20project%20for%20Node.js,%20a%20JavaScript%20runtime%20built%20on%20Chrome%27s%20V8%20JavaScript%20engine&file=issue.mjs,package.json&title=node.new%20Starter

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 111.81 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.anyenv/envs/nodenv/versions/16.13.0/bin/node
    Yarn: 1.22.17 - ~/.anyenv/envs/nodenv/versions/16.13.0/bin/yarn
    npm: 8.10.0 - ~/.anyenv/envs/nodenv/versions/16.13.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 105.0.3
    Safari: 16.0
  npmPackages:
    @vanilla-extract/css: ^1.11.0 => 1.11.0
    @vanilla-extract/esbuild-plugin: ^2.2.2 => 2.2.2
    @vanilla-extract/vite-plugin: ^3.8.2 => 3.8.2
    esbuild: ^0.17.19 => 0.17.19
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dadajam4** [comment]
Supplementation. This reproduces not only the `@layer` rule, but also atrule like `@media`.

```ts
export const a1 = globalStyle(':root', {
  '@media': {
    all: {
      color: 'red'
    }
  }
});

export const a2 = globalStyle(':root', {
  '@media': {
    all: {
      background: 'red'
    }
  }
});

```

↓ output

```css
@media all {
  :root {
    background: red;
  }
}
```

別のセレクタを指定した場合、問題は再現しません。

```ts
export const a1 = globalStyle(':root', {
  '@media': {
    all: {
      color: 'red'
    }
  }
});

export const a2 = globalStyle('.hoge', {
  '@media': {
    all: {
      background: 'red'
    }
  }
});
```

↓ output

```css
@media all {
  :root {
    color: red;
  }
  .hoge {
    background: red;
  }
}
```
