### ISSUE TITLE
Support @page (print media styles in general)

### ISSUE THREAD

**Issue by airtonix** [vanilla-extract-css/vanilla-extract#1279]
looking at how I can write this with vanilla-extract? thoughts?

```css

.pagedjs_page {
  background: white;
  box-shadow: 10px 12px 30px 0 rgba(0, 0, 0, 0.1);
  margin: 1rem;

  @page {
    size: A4;

    @bottom-right {
      content: counter(page);
    }
  }
}
```

_Originally posted by @airtonix in https://github.com/vanilla-extract-css/vanilla-extract/discussions/1275_
