### ISSUE TITLE
When using "globalStyle" with "layer" styles are missing from generated css output if the same selector is used multiple times

### ISSUE THREAD

**Issue by trongnd** [vanilla-extract-css/vanilla-extract#1417]
### Describe the bug

When using `globalStyle()` with `layer()`, if the same selector is used to define css rules multiple times with `globalStyle`, only rules from the last `globalStyle` call are found in generated css output, rules from other calls before the last one are missing.

```typescript
// Component.css.ts

import { layer, style, globalStyle } from '@vanilla-extract/css';

const testLayer = layer();

export const test = style({});

// please notice same "test" selector are used 2 times to define different css rules with "globalStyle"

globalStyle(test, {
  '@layer': {
    // rules defined here are missing from generated css output
    [testLayer]: { color: 'black' },
  },
});

globalStyle(test, {
  '@layer': {
    // rules defined here are correctly generated in css output
    // this is the last call of "globalStyle" for "test" selector
    [testLayer]: { fontSize: 16 },
  },
});
```

 ```typescript
// Component.tsx

import * as styles from './Component.css';

export default function test() {
  return <div css={styles.test}>test</div>;
}
```

```css
// generated css output
// it only has css properties defined from last rule
// "color: black" from the first "globalStyle(test)" call is missing

@layer Component_testLayer__1n2kpd00;
@layer Component_testLayer__1n2kpd00 {
  .Component_test__1n2kpd01 {
    font-size: 16px;
  }
}
```

I found the cause of this issue is from this line:
https://github.com/vanilla-extract-css/vanilla-extract/blob/e7d79f2770cf7a8b3bc64ecbd45be19a8f79a896/packages/css/src/conditionalRulesets.ts#L199 

When I update it as below code the issue is gone. 
```typescript
selectors[rule.selector] = { ...selectors[rule.selector], ...rule.rule };
``` 

Please help to fix this as my code structure is relying this pattern quite a lot and it's blocker for me ATM. Thanks team!

### Reproduction

https://not-available

### System Info

```shell
Not Available
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
